### ISSUE TITLE
maintained?

### ISSUE THREAD

**Issue by thisconnect** [studio-b12/tape-css#7]
Hi is tape-css still used / maintained? 

i.e. all the 3 PR's are closed https://github.com/studio-b12/tape-css/issues/6

**Comment by ghost** [comment]
Hello @thisconnect ,
During our high-stress phaes, we weren't able to maintain our github projects.

According to your question: Yes, we're still using tape-css. I'll take a look on #6 and inform you here back!
Thx for your interest!

**Comment by ghost** [comment]
Hello again,

There is an adjustment needed related with insert-css (PR 17 on #6). After that, I will release a stable version. This can take couple of days.
Thx again!

**Comment by thisconnect** [comment]
no problem, thanks for the info.
